
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AcervoWSService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/acervo?wsdl")
public class AcervoWSService
    extends Service
{

    private final static URL ACERVOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACERVOWSSERVICE_EXCEPTION;
    private final static QName ACERVOWSSERVICE_QNAME = new QName("http://service/", "AcervoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/acervo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACERVOWSSERVICE_WSDL_LOCATION = url;
        ACERVOWSSERVICE_EXCEPTION = e;
    }

    public AcervoWSService() {
        super(__getWsdlLocation(), ACERVOWSSERVICE_QNAME);
    }

    public AcervoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACERVOWSSERVICE_QNAME, features);
    }

    public AcervoWSService(URL wsdlLocation) {
        super(wsdlLocation, ACERVOWSSERVICE_QNAME);
    }

    public AcervoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACERVOWSSERVICE_QNAME, features);
    }

    public AcervoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcervoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcervoWS
     */
    @WebEndpoint(name = "AcervoWSPort")
    public AcervoWS getAcervoWSPort() {
        return super.getPort(new QName("http://service/", "AcervoWSPort"), AcervoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcervoWS
     */
    @WebEndpoint(name = "AcervoWSPort")
    public AcervoWS getAcervoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AcervoWSPort"), AcervoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACERVOWSSERVICE_EXCEPTION!= null) {
            throw ACERVOWSSERVICE_EXCEPTION;
        }
        return ACERVOWSSERVICE_WSDL_LOCATION;
    }

}
