
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AcervoWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AcervoWS {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verInfosAlbuns", targetNamespace = "http://service/", className = "service.VerInfosAlbuns")
    @ResponseWrapper(localName = "verInfosAlbunsResponse", targetNamespace = "http://service/", className = "service.VerInfosAlbunsResponse")
    @Action(input = "http://service/AcervoWS/verInfosAlbunsRequest", output = "http://service/AcervoWS/verInfosAlbunsResponse")
    public List<String> verInfosAlbuns();

    /**
     * 
     * @param produtoras
     * @param ano
     * @param nome
     * @return
     *     returns service.Album
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarAlbum", targetNamespace = "http://service/", className = "service.CadastrarAlbum")
    @ResponseWrapper(localName = "cadastrarAlbumResponse", targetNamespace = "http://service/", className = "service.CadastrarAlbumResponse")
    @Action(input = "http://service/AcervoWS/cadastrarAlbumRequest", output = "http://service/AcervoWS/cadastrarAlbumResponse")
    public Album cadastrarAlbum(
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "produtoras", targetNamespace = "")
        String produtoras,
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

    /**
     * 
     * @return
     *     returns java.util.List<service.Album>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verAlbuns", targetNamespace = "http://service/", className = "service.VerAlbuns")
    @ResponseWrapper(localName = "verAlbunsResponse", targetNamespace = "http://service/", className = "service.VerAlbunsResponse")
    @Action(input = "http://service/AcervoWS/verAlbunsRequest", output = "http://service/AcervoWS/verAlbunsResponse")
    public List<Album> verAlbuns();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verAlbums", targetNamespace = "http://service/", className = "service.VerAlbums")
    @ResponseWrapper(localName = "verAlbumsResponse", targetNamespace = "http://service/", className = "service.VerAlbumsResponse")
    @Action(input = "http://service/AcervoWS/verAlbumsRequest", output = "http://service/AcervoWS/verAlbumsResponse")
    public List<String> verAlbums();

    /**
     * 
     * @param ano
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verAlbunsPorAno", targetNamespace = "http://service/", className = "service.VerAlbunsPorAno")
    @ResponseWrapper(localName = "verAlbunsPorAnoResponse", targetNamespace = "http://service/", className = "service.VerAlbunsPorAnoResponse")
    @Action(input = "http://service/AcervoWS/verAlbunsPorAnoRequest", output = "http://service/AcervoWS/verAlbunsPorAnoResponse")
    public List<String> verAlbunsPorAno(
        @WebParam(name = "ano", targetNamespace = "")
        int ano);

}
